version: "3"
services:
  nhg-attendance-be:
    build:
      context: ./server
    environment:
      - NODE_ENV=production
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - BACKEND_URL=${BACKEND_URL}
      - REDIS_HOST=redis
      - DB=mongodb://mongo/nhg-attendance
      - TZ=Asia/Ho_Chi_Minh
    links:
      - mongo
      - redis

  nhg-attendance-web:
    build:
      context: ./web
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}/api

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # build:
    #   context: ./nginx
    links:
      - nhg-attendance-be
      - nhg-attendance-web
    ports:
      - 9000:80

  mongo:
    image: mongo
    ports:
      - 27017:27017

    volumes:
      - ./data/mongo:/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
